/*** Compiler Front-End Test automatically generated by the BNF Converter ***/
/*                                                                          */
/* This test will parse a file, print the abstract syntax tree, and then    */
/* pretty-print the result.                                                 */
/*                                                                          */
/****************************************************************************/
#include <stdio.h>
#include <string.h>
#include <iostream>
#include <stdexcept>
#include "Parser.H"
#include "Printer.H"
#include "Absyn.H"
#include "Typechecker.H"
#include "CodeGen.H" 

void usage() {
  printf("usage: Call with one of the following argument combinations:\n");
  printf("\t--help\t\tDisplay this help message.\n");
  printf("\t(no arguments)	Parse stdin verbosely.\n");
  printf("\t(files)\t\tParse content of files verbosely.\n");
  printf("\t-s (files)\tSilent mode. Parse content of files silently.\n");
}

int main(int argc, char ** argv)
{
  FILE *input = stdin;

  /* int quiet = 0;
  char *filename = NULL;

  if (argc > 1) {
    if (strcmp(argv[1], "-s") == 0) {
      quiet = 1;
      if (argc > 2) {
        filename = argv[2];
      } else {
        input = stdin;
      }
    } else {
      filename = argv[1];
    }
  }

  if (filename) {
    input = fopen(filename, "r");
    if (!input) {
      usage();
      exit(1);
    }
  } else input = stdin; */
  /* The default entry point is used. For other options see Parser.H */
  Prog *parse_tree;
  try{
  parse_tree = pProg(input);
  if (!parse_tree){
    throw std::runtime_error("hi");
  }
/*         printf("\n[Abstract Syntax]\n");
      ShowAbsyn *s = new ShowAbsyn();
      printf("%s\n\n", s->show(parse_tree));
      printf("[Linearized Tree]\n");
      PrintAbsyn *p = new PrintAbsyn();
      printf("%s\n\n", p->print(parse_tree)); */
  Skeleton checker;
  parse_tree->accept(&checker);
  }
  catch(std::runtime_error &e){
/*     std::cerr << "ERROR: " << e.what() << std::endl; 
 */    std::cerr << "ERROR";
    return 1;
  }
/*         printf("\n[Abstract Syntax]\n");
      ShowAbsyn *s = new ShowAbsyn();
      printf("%s\n\n", s->show(parse_tree));
      printf("[Linearized Tree]\n");
      PrintAbsyn *p = new PrintAbsyn();
      printf("%s\n\n", p->print(parse_tree)); */
  std::cerr << "OK";
   CodeGen llvm;
  parse_tree->accept(&llvm); 
  return 0;
}
